### ISSUE TITLE
Loged in users cannot submit a form

### ISSUE THREAD

**Issue by cepheiVV** [einpraegsam/powermail#549]
When a fe_user is loged in to the frontend and tries to submit a powermail form, the `MailFactory` will load the fe_user data and add it to the E-Mail;
https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Factory/MailFactory.php#L73

The `$userRepository->findByUid` however doesn't return the user data. Instead `null` is returned.

This will cause an error in the next step when the user data should be set to the Mail Model, since the `Mail::setFeuser` method requires the `$feuser` parameter to be of type `In2code\Powermail\Domain\Model\User`:
https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Model/Mail.php#L268

Testing with;
Powermail: 8.1.0
TYPO3: 10.4.4

Expected behaviour: 
 - The `$userRepository->findByUid` must return the correct user data.
 - The Mail Factory must validate the fetched user data before setting it to the Mail Model; 
    See PR: #550

**Comment by einpraegsam** [comment]
That should be fixed in latest version

**Comment by cepheiVV** [comment]
it is not

**Comment by benjaminLedel** [comment]
The issue remains unresolved because the repository's return type can potentially be null:

Here’s a quick fix for the UserRepository in the latest version:

```
public function findByUid($uid): ?User
{
    $query = $this->createQuery();
    $query->getQuerySettings()->setRespectStoragePage(false);
    $query->matching($query->equals('uid', $uid));
    /** @var User|null $user */
    $user = $query->execute()->getFirst();
    return $user;
}
```
